# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Landmark Remark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Landmark Remark
#  pod 'Firebase'  #Force Firebase/Core to import missing .h files
  pod 'Firebase/Database'
  pod 'FirebaseFirestoreSwift'#, '8.3.0-beta'  # Beta almost working for M1 but 7.5.0-beta might be most realiable

end

# Attempted fix for M1 mac but will have to leave this untested and move to Rosetta

#post_install do |installer|
#  installer.pods_project.build_configurations.each do |config|
#    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#  end
#end
